# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-Bzip2
version:      0.01
version_from: lib/PerlIO/via/Bzip2.pm
installdirs:  site
requires:
    Compress::Bzip2:               1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
